export { getCartDetails } from './get-cart-details'
export { calcCartItemTotalPrice } from './calc-cart-item-total-price'
export { calcTelephonePrice } from './calc-telephone-price'
export { getAvailableTelephoneColors } from './get-available-telephone-colors'
export { getTelephoneDetails } from './get-telephone-deteils'
export { sendEmail } from './send-email'
export { createPayment } from './create-payment'
