import { Description } from '@radix-ui/react-dialog'
import { title } from 'process'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			DASHBOARD HEADER
			<body>{children}</body>
		</html>
	)
}

// export const metadata = {
// 	title: 'Next.js',
// 	description: 'Generated by Next.js',
// }

// export default function DashboardLayout({
// 	children,
// }: {
// 	children: React.ReactNode
// }) {
// 	return (
// 		<html lang='en'>
// 			<body>
// 				DASHBOARD HEADER
// 				{children}
// 			</body>
// 		</html>
// 	)
// }
