import { Header } from '@/components/shared'
import { Container } from '@/components/shared/container'

export const metadata = {
	title: 'Glance | Кошик',
	description: 'Generated by Next.js',
}

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<Container>
			<main className='min-h-screen'>
				<Header
					hasSearch={false}
					hasCart={false}
					className='border-b-gray-200'
				/>
				{children}
			</main>
		</Container>
	)
}
